name: minify Lua files

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Luamin
        run: npm install -g luamin

      - name: Test luamin and force fail
        run: |
          find . -name "*.lua" -not -path "./.git/*" -exec sh -c '
            echo "file: $1"
            luamin --file $1
            echo ""
          ' _ {} \;

          exit 1

      - name: Make archive thingy
        run: |
          zip -r minified.zip . -x "*.git*" -x "*.github*"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-minified
          name: "Latest build"
          body: "Actions build."
          draft: false
          prerelease: false
          files: minified.zip