name: minify Lua files

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Luamin
        run: npm install -g luamin

      - name: Minify Lua files
        run: |
          find . -name "*.lua" -not -path "./.git/*" -exec sh -c '
            for file do
              tmp=$(mktemp)

              if luamin -f "$file" > "$tmp" 2>err.log; then
                mv "$tmp" "$file"
                echo "$file minified."
              else
                echo "fuckkk"
                cat err.log
                rm "$tmp"
                rm err.log
                exit 1
              fi
            done
          ' _ {} +

      - name: Make archive thingy
        run: |
          zip -r minified.zip . -x "*.git*" -x "*.github*"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-minified
          name: "Latest build"
          body: "Actions build."
          draft: false
          prerelease: false
          files: minified.zip